2023-10-16 15:19:18.781 Uncaught app exception Traceback (most recent call last):   File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script     exec(code, module.__dict__)   File "/mount/src/qwaixx/streamlit_app.py", line 101, in <module>     game_engine.make_move() TypeError: make_move() missing 1 required positional argument: 'selections'
2023-10-16 15:19:18.781 Uncaught app exception
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/mount/src/qwaixx/streamlit_app.py", line 101, in <module>
    game_engine.make_move()
TypeError: make_move() missing 1 required positional argument: 'selections'